image: gradle:alpine

stages:
  - build
  - test
  - sonarqube
  - deploy_dev
  - deploy_qa
  - deploy_prod

before_script:
  - set GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - gradle/wrapper
    - build
    
build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/ProyectoEverest.jar
  tags:
      - localhostRunner
test:
  stage: test
  script:
    - ./gradlew test
  tags:
      - localhostRunner

sonarqube:
  stage: sonarqube
  script: 
    - ./gradlew sonarqube
  tags:
      - localhostRunner

deploy_dev:
  stage: deploy_dev
  script:
    - gradle run
  only:
    - master
  tags:
      - localhostRunner

deploy_qa:
  stage: deploy_qa
  script:
    - gradle run
  only:
    - qa
  tags:
      - localhostRunner
  when: manual
    
deploy_prod:
  stage: deploy_prod
  script:
    - gradle run
  only:
    - prod
  tags:
      - localhostRunner
  when: manual