image: gradle:alpine

before_script:
  - set GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - sonarqube
  - deploy_dev
  - deploy_qa
  - deploy_prod

build:
  stage: build
  script:
    - gradle clean && gradle build
  artifacts:
    paths:
      - build/libs/*.jar
  tags:
      - gitlab-org
test:
  stage: test
  script:
    - gradle test
  tags:
      - gitlab-org

sonarqube:
  stage: sonarqube
  script: 
    - gradle sonarqube
  tags:
      - gitlab-org

deploy_dev:
  stage: deploy_dev
  script:
    - gradle run
  only:
    - master
  tags:
      - gitlab-org

deploy_qa:
  stage: deploy_qa
  script:
    - gradle run
  only:
    - qa
  tags:
      - gitlab-org
  when: manual
    
deploy_prod:
  stage: deploy_prod
  script:
    - gradle run
  only:
    - prod
  tags:
      - gitlab-org
  when: manual